directories:
  output: build
  buildResources: build
productName: selfServiceTerminals
appId: com.example.yourapp
extraResources:
  - static
files:
  - dist/electron/**/*
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
publish:
  - provider: generic
    url: 'http://127.0.0.1:8888/'
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
linux:
  icon: build/icons
electronVersion: 3.1.0
